### ISSUE TITLE
Separate SDK import and CLI

### ISSUE THREAD

**Issue by novalagung** [franzramadhan/cidrlist#3]
Hi mas @franzramadhan, really love this project! It is exactly the package I'm looking for.

Based on the details on README.md, I believe this project is only designed for CLI purposes. I think it would be great if we could also use this package as an importable dependency. Therefore, I'm proposing the changes on [this PR](https://github.com/franzramadhan/cidrlist/pull/2).

I put the changelog details there, kindly review. Thanks!

**Comment by franzramadhan** [comment]
@novalagung thanks for raising this one. Really useful and looking forward to learning more from you 😁
